Repository Panoptimize/BackEnd, pull requests merged in 2024-05, with the labels that each got.

#71 Customer Satisfaction BackEnd commit
  pom.xml
  src/main/java/com/itesm/panoptimize/config/RestTemplateConfig.java
  src/main/java/com/itesm/panoptimize/config/WebClientConfig.java
  src/main/java/com/itesm/panoptimize/controller/DashboardController.java
  src/main/java/com/itesm/panoptimize/dto/dashboard/CallMetricsDTO.java
  src/main/java/com/itesm/panoptimize/service/CalculateSatisfactionService.java
Labels: enhancement

#66 First Response Contact KPI
  pom.xml
  src/main/java/com/itesm/panoptimize/config/Constants.java
  src/main/java/com/itesm/panoptimize/controller/DashboardController.java
  src/main/java/com/itesm/panoptimize/controller/DashboardDataController.java
  src/main/java/com/itesm/panoptimize/dto/dashboard/DashMetricData.java
  src/main/java/com/itesm/panoptimize/dto/dashboard/DashboardDataDTO.java
  src/main/java/com/itesm/panoptimize/dto/dashboard/MetricsDTO.java
  src/main/java/com/itesm/panoptimize/dto/metric/Threshold.java
  src/main/java/com/itesm/panoptimize/service/DashboardDataService.java
  src/main/java/com/itesm/panoptimize/service/FCRService.java
Labels: enhancement

#68 Main dashboard KPI's filtering
  env.sample
  pom.xml
  src/main/java/com/itesm/panoptimize/config/ConnectSimulation.java
  src/main/java/com/itesm/panoptimize/config/Constants.java
  src/main/java/com/itesm/panoptimize/config/ModelMapperConfiguration.java
  src/main/java/com/itesm/panoptimize/controller/AgentController.java
  src/main/java/com/itesm/panoptimize/controller/DashboardController.java
  src/main/java/com/itesm/panoptimize/dto/dashboard/DashboardDTO.java
  src/main/java/com/itesm/panoptimize/dto/dashboard/MetricsDTO.java
  src/main/java/com/itesm/panoptimize/dto/dashboard/metric/Filter.java
  src/main/java/com/itesm/panoptimize/dto/dashboard/metric/Interval.java
  src/main/java/com/itesm/panoptimize/dto/dashboard/metric/Metric.java
  src/main/java/com/itesm/panoptimize/dto/dashboard/metric/MetricFilter.java
  src/main/java/com/itesm/panoptimize/dto/dashboard/metric/RequestMetricDataV2.java
  src/main/java/com/itesm/panoptimize/dto/dashboard/metric/Threshold.java
  src/main/java/com/itesm/panoptimize/dto/metric/Filters.java
  src/main/java/com/itesm/panoptimize/dto/metric/HistoricalMetric.java
  src/main/java/com/itesm/panoptimize/dto/metric/MetricRequest.java
  src/main/java/com/itesm/panoptimize/repository/UserRepository.java
  src/main/java/com/itesm/panoptimize/service/DashboardService.java
  src/main/java/com/itesm/panoptimize/service/FCRService.java
  src/main/java/com/itesm/panoptimize/service/UserService.java
Labels: help wanted

#81 Update task-definition.json
  .github/workflows/task-definition.json
Labels: enhancement

#85 Task definition
  .github/workflows/main.yml
Labels: bug

#87 Task definition
  .github/workflows/main.yml
Labels: bug

#97 Agent list and Agent Details
  .gitignore
  src/main/java/com/itesm/panoptimize/.DS_Store
  src/main/java/com/itesm/panoptimize/controller/AgentController.java
  src/main/java/com/itesm/panoptimize/controller/DashboardController.java
  src/main/java/com/itesm/panoptimize/controller/StatusController.java
  src/main/java/com/itesm/panoptimize/dto/agent/AgentDetailsDTO.java
  src/main/java/com/itesm/panoptimize/dto/agent/IdentityInfoDTO.java
  src/main/java/com/itesm/panoptimize/dto/agent/StatusDTO.java
  src/main/java/com/itesm/panoptimize/dto/dashboard/AWSObjDTO.java
  src/main/java/com/itesm/panoptimize/dto/dashboard/DashboardDTO.java
  src/main/java/com/itesm/panoptimize/dto/dashboard/DashboardFiltersDTO.java
  src/main/java/com/itesm/panoptimize/dto/dashboard/MetricResponseDTO.java
  src/main/java/com/itesm/panoptimize/service/AgentListService.java
  src/main/java/com/itesm/panoptimize/service/DashboardService.java
  src/main/java/com/itesm/panoptimize/service/StatusService.java
Labels: enhancement
