Repository Panoptimize/BackEnd, pull requests merged in 2024-06, with the labels that each got.

#123 Testing
  src/main/java/com/itesm/panoptimize/controller/AgentController.java
  src/main/java/com/itesm/panoptimize/dto/agent/AgentCreateDTO.java
  src/main/java/com/itesm/panoptimize/dto/agent/AgentUserDTO.java
  src/main/java/com/itesm/panoptimize/dto/supervisor/SupervisorCreateDTO.java
  src/main/java/com/itesm/panoptimize/dto/supervisor/SupervisorDTO.java
  src/main/java/com/itesm/panoptimize/dto/supervisor/SupervisorUpdateDTO.java
  src/main/java/com/itesm/panoptimize/dto/supervisor/SupervisorUserDTO.java
  src/main/java/com/itesm/panoptimize/model/User.java
  src/main/java/com/itesm/panoptimize/service/UserService.java
  src/test/java/com/itesm/panoptimize/AgentControllerTests.java
  src/test/java/com/itesm/panoptimize/DownloadControllerTests.java
  src/test/java/com/itesm/panoptimize/PanoptimizeApplicationTests.java
Labels: enhancement

#157 Tests de la historia de usuario Notes
  src/main/java/com/itesm/panoptimize/service/NoteService.java
  src/test/java/com/itesm/panoptimize/NoteTests.java
Labels: documentation

#160 Añadir Transactional y Rollback al test de testGetAgentPerformanceByN…
  src/test/java/com/itesm/panoptimize/NoteTests.java
Labels: bug

#167 Supervisor info test
  src/test/java/com/itesm/panoptimize/SupervisorControllerTest.java
Labels: documentation

#165 Corrections to AgentControllerTest FirebaseConfig
  .gitignore
  src/test/java/com/itesm/panoptimize/AgentControllerTests.java
Labels: enhancement
